POST /api/inventry HTTP/1.1
Host: localhost:5000
Content-Type: application/json
Accept: application/json

{
    "stock_unit":"inventry-1",
    "open_stock":10,
    "low_warning":true,
    "lower_limit":2,
    "name":"item6",
    "item_code":"i-006",
    "category":"C6",
    "item_detail":"test item 6 with inventry",
    "amount":"400",
    "item_type":"A-1",
    "item_image":"www.google.com/hehehehehe",
    "tax_rate":35,
    "date":"21/07/2021"
}