PUT /api/inventry HTTP/1.1
Host: localhost:5000
Content-Type: application/json
Accept: application/json

{
    "itemId":"60fb020fac6fa11d1056e992",
    "inventryId":"60fb020fac6fa11d1056e994",
    "stock_unit":"inventry-1",
    "open_stock":10,
    "low_warning":true,
    "lower_limit":2,
    "name":"item4-6",
    "item_code":"i-004.6",
    "item_detail":"test item 4-6 with inventry",
    "amount":600,
    "item_type":"A-6"
}