POST /api/item HTTP/1.1
Host: localhost:5000
Content-Type: application/json
Accept: application/json

{
    "name":"item2",
    "item_code":"i-002",
    "category":"C2",
    "item_detail":"test item 2",
    "amount":"200",
    "item_type":"A",
    "item_image":"https://fkajbfkjabfjkabfkhebkjeb",
    "tax_rate":5
}